### ISSUE TITLE
Platformio registry lists very old version and is outdated

### ISSUE THREAD

**Issue by thijstriemstra** [khoih-prog/ESP8266TimerInterrupt#11]
https://platformio.org/lib/show/6901/ESP8266TimerInterrupt

shows 1.0.3 as latest version, although it should be 1.4.0, no?

**Comment by khoih-prog** [comment]
Thanks for your interest in the library.

This is an issue of PIO, discussed many times as they also happen to many other libraries of mine. For example [PlatformIO only has version 1.3.0 #65](https://github.com/khoih-prog/ESP_WiFiManager/issues/65), etc.

You have to use the latest one as in [**Latest PIO ESP8266TimerInterrupt**](https://platformio.org/lib/show/11385/ESP8266TimerInterrupt) according to [**Installation for VS Code & PlatformIO**](https://github.com/khoih-prog/ESP8266TimerInterrupt#vs-code--platformio).

That's why I had to create a new author `khoih.prog` to replace the outdated `khoih-prog`

Regards,

**Comment by thijstriemstra** [comment]
Gotcha, thanks!
