### ISSUE TITLE
One shot operating mode

### ISSUE THREAD

**Issue by absalom-muc** [khoih-prog/ESP8266TimerInterrupt#20]
I use your lib for periodic interrupts - works like a charm, thank you for that!

Addtionally I would like to use it in an one shot operating mode. So the interrupt should be triggered only once. It could be also solved by providing a duration as described [here](https://github.com/khoih-prog/ESP8266TimerInterrupt#12-set-hardware-timer-interval-and-attach-timer-interrupt-handler-function), but when my understanding is correct, the duration is not implemented so far.

Edit: Maybe there could be a way to detach an interrupt, e.g. by providing a reference by ITimer.attachInterruptInterval

**Comment by khoih-prog** [comment]
Hi @absalom-muc 

The new [**ESP8266TimerInterrupt releases v1.6.0**](https://github.com/khoih-prog/ESP8266TimerInterrupt/releases/tag/v1.6.0) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP8266TimerInterrupt#contributions-and-thanks)

You can try [**ISR_16_Timers_Array_OneShot** example](examples/ISR_16_Timers_Array_OneShot) to see how to use `one-shot ISR-based timer`

Best Regards,

---

### Releases v1.6.0

1. Add example [**ISR_16_Timers_Array_OneShot**](examples/ISR_16_Timers_Array_OneShot) to demo how to use `one-shot ISR-based timer`
2. Add example [**multiFileProject**](examples/multiFileProject) to demo for multiple-file project
3. Optimize code by using passing by `reference` instead of by `value`

**Comment by absalom-muc** [comment]
Thank you very much @khoih-prog! I appreciate your quick feedback.
