### ISSUE TITLE
Deepsleep functionality

### ISSUE THREAD

**Issue by tech-freak** [khoih-prog/ESP8266TimerInterrupt#3]
Hello , sorry for asking for improvement via issue 

is there any plan to add deep sleep functionality and time fetch from NTP (to keep time up-to-date) ? for making it battery friendly project

i have tried ESPDailyTaskNTP but that works like hit and try , not even managed by dev now

**Comment by khoih-prog** [comment]
Hi, 
Thanks for using the library. 
Don't think too negative about asking improvement, as many times, new ideas start from so-called unusual requirements and from real-life applications.
In this case, I'm sorry that the mentioned improvement can't be added to this specific library because it's written for special cases dealing with ESP8266 Timer and Interrupt.

You can find many libraries, examples dealing with the specific issues you experience such as **DeepSleep, NTP time**.

You can check some of my Sample Projects dealing with ESP8266/ESP32 DeepSleep as well as using TimerInterrupt in

1. [SmallProjects](https://github.com/khoih-prog/SmallProjects)
2. [SmartFarm_DeepSleep](https://github.com/khoih-prog/SmallProjects/tree/master/SmartFarm_DeepSleep)
3. [MasterController](https://github.com/khoih-prog/SmallProjects/tree/master/MasterController)
4. [ISR_FireSmokeAlarm](https://github.com/khoih-prog/SmallProjects/tree/master/ISR_FireSmokeAlarm)
....

There are also many more libraries in my GitHub you can try and use at:

[My Repositories](https://github.com/khoih-prog)

Please don't hesitate to ask for improvement next time.

Regards,

**Comment by tech-freak** [comment]
okay , thank you

i am looking for simple lib which can allow to wake at specific 2 time /day , i am working on pet feeder and i don't want to use blynk

i'll be really thankful if you can look above lib and make it batter

**Comment by khoih-prog** [comment]
I'll have a look at that features and see what I can do to make an example or library. But can't promise or do anything until I'm finishing the current tasks. Will let you know when time comes.

**Comment by tech-freak** [comment]
Okay , thank you
please reply here once done so i get notified
