### ISSUE TITLE
Possible error in RPM_Measure.ino

### ISSUE THREAD

**Issue by Win-doze** [khoih-prog/ESP8266TimerInterrupt#4]
I was looking at you code for RPM_Measure.ino to understand this library as it does not 'play nicely' with your servo library. You calculate avgRPM in the program then never use it.
should the line:
Serial.println("RPM = " + String(RPM) + ", rotationTime ms = " + String(rotationTime * TIMER_INTERVAL_MS) );
be:
Serial.println("RPM = " + String(avgRPM) + ", rotationTime ms = " + String(rotationTime * TIMER_INTERVAL_MS) );

Anyway, if you can suggest which library would be best to run one servo and run a short routine exactly every 20 miliseconds I would appreciate it.

**Comment by khoih-prog** [comment]
Hi @Win-doze 

Thanks for showing the mistake which will be fixed in next release.

>  library would be best to run one servo and run a short routine exactly every 20 miliseconds I would appreciate it.

You can try [ESP8266_ISR_Servo](https://github.com/khoih-prog/ESP8266_ISR_Servo) to control servos and use this [ESP8266TimerInterrupt](https://github.com/khoih-prog/ESP8266TimerInterrupt) to call your routine exactly every 20ms.
